---
title: "fatbird"
author: "Hoang An"
date: "12/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
load("~/M2/Professional project/puffin_scopoli/grid_oceano_2011.Rdata")
load("~/M2/Professional project/puffin_scopoli/grid_oceano_Date_2011.Rdata")
```

```{r}
library(lubridate)
library(ggmap)
```

```{r}
summary(grid_oceano) #95 dataframe
summary(grid_Oceano_Date) #95 days
bird1 <- grid_oceano[[1]]
summary(bird1)
```

```{r}
## variables explore


```

```{r}
#make box for cutting on map
bc_bbox <- make_bbox(lat = Latitude, lon = Longitude, data = bird1)
bc_bbox

# grab the maps from google
day1 <- get_map(location = bc_bbox, source = "google", maptype = "terrain")
```
```{r}
g <- ggmap(day1) + 
    geom_point(data = bird1, mapping = aes(
                            x = Longitude, 
                            y = Latitude,
                          color = Dist),
                          size = 1, alpha = .4)+
#    scale_colour_gradientn(colours = c("black","deepskyblue","red","green"),
#                            trans = "log",
                            #values = c(0,0.035,0.0625,1),
                            #limits = c(0,1),
#                            na.value = "grey50")+
    ggtitle("Map day 1") +
    xlab("UTM Easting Coordinate") +
    ylab("UTM Northing Coordinate")
    
g
```

```{r}
## variables explore
hist(bird1$Cell) #uniform
plot(x = bird1$Longitude, y = bird1$Latitude)
hist(bird1$Dist)
summary(bird2$Dist
        )
```
```{r}
bird2 <- grid_oceano[[2]]

bc_bbox <- make_bbox(lat = Latitude, lon = Longitude, data = bird2)
bc_bbox

# grab the maps from google
day2 <- get_map(location = bc_bbox, source = "google", maptype = "terrain")
map <- ggmap(day2)

g <- ggmap(day2) +
      geom_point(data = bird2, mapping = aes(
                            x = Longitude, 
                            y = Latitude,
                          color = SST1),
                          size = 2, alpha = 0.4)+
  scale_colour_gradientn(colours = terrain.colors(200),
                           na.value = NA)
    
g
```
