---
title: "Integrated step selection analysis (iSSA)"
author: "Pierre Cottais & An Hoàng"
date: "25/01/2022"
output: 
  pdf_document: 
    extra_dependencies: ["float"]
    toc: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      results = "hide")
```

```{r packages}
library(tidyverse)
library(lubridate)
library(amt)
library(stargazer)
```



# Data processing
```{r}
# oceanography dataset
load("CALDIO_MPE_2021/generalisation datasets/grid_oceano_2011.Rdata")
load("CALDIO_MPE_2021/generalisation datasets/grid_oceano_Date_2011.Rdata")

# Scopoli's sheawater datasets
load("CALDIO_MPE_2021/training datasets/CALDIO_2011_oceano.Rdata")
load("CALDIO_MPE_2021/training datasets/CALDIO_2012_oceano.Rdata")

# load functions
source("functions.R")
```



# Steps of Giraglia colony
```{r}
# observed + available steps
start <- Sys.time()
stps <- iSSA_steps(colony = "Giraglia", year = 2011,
             # covariates = colnames(grid_oceano[[1]][,8:41]))
             covariates = c("Bathy", "GBathy", "SST28", "GSST28", "Var_SST28",
                            "SLA1", "VEL7", "logCHLA28", "GCHLA28"))
end <- Sys.time()
print(end-start)

# iSSA conditional regression model
mod_G <- stps %>% amt::fit_issf(case_ ~ sl_ + ta_ + log_sl + Bathy + GBathy +
                                  SST28 + GSST28 + Var_SST28 + SLA1 + VEL7 +
                                  logCHLA28 + GCHLA28 + strata(step_id_))
mod_G$model
```


```{r}
# initialisation
models <- list()

# running the analysis
start <- Sys.time()
for (site in unique(ALL2011$Site)){
  steps <- iSSA_steps(colony = site, year = 2011,
                      covariates = c("Bathy", "GBathy", "SST28", "GSST28", "Var_SST28",
                                     "SLA1", "VEL7", "logCHLA28", "GCHLA28"))
  models[[site]] <- stps %>% amt::fit_issf(case_ ~ sl_ + ta_ + log_sl + strata(step_id_))
}
end <- Sys.time()
print(end-start)


```


```{r}
# compare the 4 models
models$Riou$model
models$Lavezzi$model
models$Porquerolles$model
models$Giraglia$model
```

```{r}
cor(ALL2011$SST28, ALL2011$logCHLA28)

```

