---
title: "Animal movement simulation"
author: "Pierre Cottais & An Hoàng"
date: "30/11/2021"
output: 
  pdf_document: 
    extra_dependencies: ["float"]
    toc: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T,
                      results = "hide")
```


```{r packages, include=FALSE}
library(tidyverse)
library(lubridate)
library(wesanderson)
```


# Generating individual animal step lengths data (utilization distribution)

Probability of obtaining a sample at some distance, $l^{\prime}_{t,i}$ from the previous observed point ($l^{\prime}_{t,i} = || x^{\prime}_{t,i}-x$ is given by the gamma PDF:

$$g(l^{\prime}_{t,i}|b_1,b_2) = \frac{1}{\Gamma(b_1).b1^{b2}} . l_{t,i}^{\prime b_1-1}. e^{-\frac{l^{\prime}_{t,i}}{b_2}}$$

```{r}
b1 <- 10 ; b2 <- 10
n <- 100
X <- rgamma(n, scale = b1, shape = b2)
hist(X, freq=F)
x <- seq(30, 300, by = 0.1)
lines(x, dgamma(x, scale = b1, shape = b2), col = "red")
```




```{r}
s <- rep_len(1:3, 200000)
L <- c(0.01, 0.05, 0.1)
nimporte <- case_when(s == 1 ~ L[1],
                      s == 2 ~ L[2],
                      s == 3 ~ L[3])
fin <- Sys.time()
```


```{r}
# Environment grid ver2
lat <- seq(-100,100, 1)
long <- seq(-100,100, 1)
n <- length(lat)
m <- length(long)
envi <- matrix(data = runif(n*m),nrow = n, ncol = m)
colnames(envi) <- lat
row.names(envi) <- long

```


```{r}
#autocorection
p <- 5 #spatial unit

#sliding window
for (i in 1:(n-p)){
  for (j in 1:(m-p)){
    sub <- envi[i:(i+p),j:(j+p)]
    envi[i,j] = mean(sub)
  }
}
envi <- envi[1:(n-p),1:(m-p)]
```


```{r}
pal <- wes_palette(40401,name = "Zissou1", type = "continuous")
heatmap(envi, Rowv = NA, Colv = NA, col = pal)
```


```{r}
# habitat selection step
mu <- 1.7918
# chose moving length always || x- x(t) || = 1 
omega <- 1 
# #local habitat quality
envi_dt <- as.data.frame(envi)

# apply truncated redistribution calculus kernel to the whole grid-landscape
envi_exp <- exp(omega*envi-mu)

# adding two null columns at the "borders"
envi_exp <- cbind(rep(0, times = nrow(envi_exp)),
                  envi_exp,
                  rep(0, times = nrow(envi_exp)))
# adding two null rows at the "borders"
# adding two null columns at the "borders"
envi_exp <- rbind(rep(0, times = ncol(envi_exp)),
                  envi_exp,
                  rep(0, times = ncol(envi_exp)))
# envi_exp <- as.data.frame(envi_exp)

# number of burn-in steps
step1 <- 2*length(envi)^2
# number of simulate steps
step2 <- 10^5
# # starting point 
# bird <- which(envi == max(envi), arr.ind = TRUE)
```


```{r}
moves <- function(steps){
  # declare vectors to be returned in a list
  coordinates <- cbind(rep(0, steps+1), rep(0, steps+1))
  prob_avail <- matrix(0, nrow = steps+1, ncol = 9)
  num_cell <- rep(0, steps+1)
  
  # matrix of avaible movements
  code <- cbind(rep(c(-1, 0, 1), 3), rep(c(-1, 0, 1), each = 3))
  
  # starting point (deterministic)
  # coordinates[1,] <- which(envi_exp == max(envi_exp), arr.ind = TRUE)
  coordinates[1,] <- c(2, 197)
  latitude <- coordinates[1,1]
  longitude <- coordinates[1,2]
  prob_avail[1,] <- c(0, 0, 0, 0, 1, 0, 0, 0, 0)
  num_cell[1] <- 5

  
  for(i in 1:steps){
    # print(dim(kernel))
    latitude <- coordinates[i,1]
    longitude <- coordinates[i,2]
    
    kernel <- envi_exp[(latitude-1):(latitude+1),
                     (longitude-1):(longitude+1)]

    probs <- kernel/sum(kernel)
    prob_avail[i+1,] <- c(probs)

    num_cell[i+1] <- which(rmultinom(1, 1, prob_avail[i+1,])==1)
    move <- code[num_cell[i+1],]
    coordinates[i+1,] <- c(latitude+move[1], longitude+move[2])
  }
  coord_dt <- as.data.frame(coordinates, row.names = FALSE)
  colnames(coord_dt) <- c("row", "col")
  list_avail <- list(prob_avail, num_cell)
  return(list(coord_dt, list_avail))
}
```


```{r}
res <- moves(100)
coord <- res[[1]]
prob <- res[[2]]

```


```{r}
hist(prob[[1]])
```


```{r}
heatmap(envi, Rowv = NA, Colv = NA, col = pal)
lines(envi_exp[coord$row, coord$col], lwd = 0.2)
# points(envi_exp[coord$row, coord$col], lwd = 0.1, pch = 3, cex = 0.2)
```



```{r}

```











```{r}
# seal <- read.csv("https://www.datarepository.movebank.org/bitstream/handle/10255/move.451/Grey%20seals%20%28Halichoerus%20grypus%29%20at%20Sable%20Island%20%28data%20from%20Baker%20et%20al.%202015%29.csv?sequence=1")
```

```{r}
# seal %>% 
#   mutate(timestamp = ymd_hms(timestamp)) %>% 
#   select(timestamp)
```

```{r}
# seal %>% 
#   filter(tag.local.identifier == 106705) %>% 
#   ggplot() + aes(x = location.long, location.lat) +
#   geom_point() + 
#   geom_line()
```

